services:
  mysql:
    image: mysql:8
    env_file:
      - credentials.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:v1.18
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage:z
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  qdrant_storage:
